language: go

sudo: required

os:
    - linux
    - osx
go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - 1.13.x
    - tip

matrix:
    allow_failures:
        - go: tip
        - os: windows
    exclude:
          # OSX 1.6.4 is not present in travis.
          # https://github.com/travis-ci/travis-ci/issues/10309
        - go: 1.6.x
          os: osx
    include:
        - os: windows
          go: 1.12.x
        - os: windows
          go: 1.13.x
        - os: windows
          go: tip
        - os: linux
          go: 1.5.x
          # Use Go 1.5's vendoring experiment for 1.5 tests.
          env: GO15VENDOREXPERIMENT=1

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      make get-deps;
      make unit-no-verify;
    else
      if [ $TRAVIS_GO_VERSION == "1.10.x" ] ||
      [ $TRAVIS_GO_VERSION == "1.11.x" ] ||
      [ $TRAVIS_GO_VERSION == "1.12.x" ] ||
      [ $TRAVIS_GO_VERSION == "1.13.x" ] ||
      [ $TRAVIS_GO_VERSION == "tip" ]; then
          make get-deps;
          make ci-test;
      else
          make get-deps-tests;
          make unit-old-go-race-cover;
      fi
    fi

branches:
  only:
    - master
