apt:
  update: true

env:
  - PROTOBUF_VERSION=2.6.1
  - PROTOBUF_VERSION=3.0.2
  - PROTOBUF_VERSION=3.7.1

before_install:
  - ./install-protobuf.sh
  - PATH=/home/travis/bin:$PATH protoc --version

script:
  - PATH=/home/travis/bin:$PATH make buildserverall
  - echo $TRAVIS_GO_VERSION
  - if [[ "$PROTOBUF_VERSION" == "3.7.1" ]] && [[ "$TRAVIS_GO_VERSION" == "1.12.x" ]]; then ! git status --porcelain | read || (git status; git diff; exit 1); fi

language: go

go:
  - 1.11.x
  - 1.12.x
