name: buf.build
on:
  pull_request:
    paths:
      - ".github/workflows/buf-lint.yml"
      - "**.proto"
jobs:
  buf:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.6.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'prompb'
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'prompb'
          against: 'https://github.com/prometheus/prometheus.git#branch=main,ref=HEAD,subdir=prompb'
